remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: "Composer"
description: "Algorithmic Composition for C++"

search_enabled: true

aux_links:
  "Composer on GitHub":
    - "//github.com/alandefreitas/composer"
  "Composer on CodeDocs":
    - "https://codedocs.xyz/alandefreitas/composer/"

aux_links_new_tab: false

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/composer/tree/master/LICENSE.txt\">MIT license.</a>"
